apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: customclusters.sde.dev
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: sde.dev
  # list of versions supported by this CustomResourceDefinition
    # either Namespaced or ClusterIP
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: customclusters
    # singular name to be used as an alias on the CLI and for display
    singular: customcluster
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Customcluster
    listKind: CustomclusterList
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cpod
  versions:
    - name: v1alpha1
      properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                Message:
                  type: string
                Count:
                  type: integer
            status:
              type: object
              properties:
                message:
                  type: string
                count:
                  type: integer
          type: object
      served: true
      storage: true
      subresources:
        status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

      
